// packages/nstreamdown/solid/components/Streamdown.tsx
/**
 * Streamdown Component for Solid
 * Main component for rendering streaming markdown content natively on iOS
 */
import { createSignal, createMemo, createEffect, onCleanup, For, Show, JSX } from 'solid-js';
import { parseMarkdown } from '@nstudio/nstreamdown';
import type { MarkdownToken } from '@nstudio/nstreamdown';

export interface StreamdownConfig {
  /** Mode: 'streaming' for real-time updates, 'static' for complete markdown */
  mode?: 'streaming' | 'static';
  /** Whether to show copy/download controls */
  controls?: boolean;
  /** Whether to animate the caret during streaming */
  showCaret?: boolean;
  /** Custom caret character */
  caret?: string;
}

export interface StreamdownProps {
  content: string;
  config?: StreamdownConfig;
  isStreaming?: boolean;
  onLinkTap?: (url: string) => void;
  onParseComplete?: () => void;
}

export function Streamdown(props: StreamdownProps): JSX.Element {
  const [markdown, setMarkdown] = createSignal('');
  let throttleTimer: ReturnType<typeof setTimeout> | null = null;
  let pendingContent = '';
  let lastUpdateTime = 0;
  const THROTTLE_MS = 32;

  // Computed values
  const mode = () => props.config?.mode || 'streaming';
  const showCaret = () => props.config?.showCaret ?? true;
  const caretChar = () => props.config?.caret || '▋';

  // Parsed result
  const parsedResult = createMemo(() => {
    const md = markdown();
    if (!md) return { tokens: [], isComplete: true };
    const isStreamingMode = mode() === 'streaming';
    return parseMarkdown(md, isStreamingMode);
  });

  const tokens = () => parsedResult().tokens;
  const isComplete = () => parsedResult().isComplete;
  const isStreamingActive = () => mode() === 'streaming' && !isComplete();

  // Watch content changes with throttling
  createEffect(() => {
    const newContent = props.content;
    const currentMode = mode();

    if (currentMode === 'streaming') {
      pendingContent = newContent;
      const now = Date.now();
      const elapsed = now - lastUpdateTime;

      if (elapsed >= THROTTLE_MS) {
        lastUpdateTime = now;
        setMarkdown(newContent);
      } else if (!throttleTimer) {
        throttleTimer = setTimeout(() => {
          throttleTimer = null;
          lastUpdateTime = Date.now();
          setMarkdown(pendingContent);
        }, THROTTLE_MS - elapsed);
      }
    } else {
      setMarkdown(newContent);
    }
  });

  // Cleanup
  onCleanup(() => {
    if (throttleTimer) {
      clearTimeout(throttleTimer);
      throttleTimer = null;
    }
  });

  // Helper functions
  const isHeading = (token: MarkdownToken): boolean => token.type.startsWith('heading');
  const getHeadingLevel = (token: MarkdownToken): number => parseInt(token.type.replace('heading', ''), 10) || 1;
  const getLanguage = (token: MarkdownToken): string => (token.metadata?.['language'] as string) || '';
  const getUrl = (token: MarkdownToken): string => (token.metadata?.['url'] as string) || '';

  const getHeadingClass = (level: number): string => {
    const sizes: Record<number, string> = {
      1: 'text-3xl font-bold',
      2: 'text-2xl font-bold',
      3: 'text-xl font-semibold',
      4: 'text-lg font-semibold',
      5: 'text-base font-medium',
      6: 'text-sm font-medium'
    };
    return sizes[level] || sizes[1];
  };

  return (
    <stacklayout class="streamdown-container">
      <For each={tokens()}>
        {(token, index) => (
          <>
            {/* Headings */}
            <Show when={isHeading(token)}>
              <label
                text={token.content}
                class={`${getHeadingClass(getHeadingLevel(token))} text-slate-800 mb-2`}
                textWrap={true}
              />
            </Show>

            {/* Paragraphs */}
            <Show when={token.type === 'paragraph'}>
              <label
                text={token.content}
                class="text-base text-slate-700 mb-3 leading-6"
                textWrap={true}
              />
            </Show>

            {/* Code blocks */}
            <Show when={token.type === 'code-block'}>
              <stacklayout class="bg-slate-800 rounded-lg p-3 mb-3">
                <Show when={getLanguage(token)}>
                  <label
                    text={getLanguage(token)}
                    class="text-xs text-slate-400 mb-2"
                  />
                </Show>
                <label
                  text={token.content}
                  class="text-sm text-green-400 font-mono"
                  textWrap={true}
                />
              </stacklayout>
            </Show>

            {/* Blockquotes */}
            <Show when={token.type === 'blockquote'}>
              <stacklayout class="border-l-4 border-slate-300 pl-4 mb-3">
                <label
                  text={token.content}
                  class="text-base text-slate-600 italic"
                  textWrap={true}
                />
              </stacklayout>
            </Show>

            {/* Ordered lists */}
            <Show when={token.type === 'list-ordered'}>
              <stacklayout class="mb-3">
                <For each={token.children || []}>
                  {(item, itemIndex) => (
                    <gridlayout columns="auto, *" class="mb-1">
                      <label col="0" text={`${itemIndex() + 1}.`} class="text-slate-500 mr-2" />
                      <label col="1" text={item.content} class="text-slate-700" textWrap={true} />
                    </gridlayout>
                  )}
                </For>
              </stacklayout>
            </Show>

            {/* Unordered lists */}
            <Show when={token.type === 'list-unordered'}>
              <stacklayout class="mb-3">
                <For each={token.children || []}>
                  {(item) => (
                    <gridlayout columns="auto, *" class="mb-1">
                      <label col="0" text="•" class="text-slate-500 mr-2" />
                      <label col="1" text={item.content} class="text-slate-700" textWrap={true} />
                    </gridlayout>
                  )}
                </For>
              </stacklayout>
            </Show>

            {/* Tables */}
            <Show when={token.type === 'table'}>
              <scrollview orientation="horizontal" class="mb-3">
                <stacklayout class="bg-white rounded-lg border border-slate-200">
                  <For each={token.children || []}>
                    {(row, rowIndex) => (
                      <gridlayout
                        columns={row.children?.map(() => '*').join(', ')}
                        class={rowIndex() === 0 ? 'bg-slate-100' : ''}
                      >
                        <For each={row.children || []}>
                          {(cell, cellIndex) => (
                            <label
                              col={cellIndex()}
                              text={cell.content}
                              class={`${rowIndex() === 0 ? 'font-semibold ' : ''}p-2 text-sm text-slate-700`}
                            />
                          )}
                        </For>
                      </gridlayout>
                    )}
                  </For>
                </stacklayout>
              </scrollview>
            </Show>

            {/* Images */}
            <Show when={token.type === 'image'}>
              <image
                src={getUrl(token)}
                class="rounded-lg mb-3"
                stretch="aspectFit"
              />
            </Show>

            {/* Horizontal rules */}
            <Show when={token.type === 'horizontal-rule'}>
              <stacklayout class="h-px bg-slate-200 my-4" />
            </Show>

            {/* Math blocks */}
            <Show when={token.type === 'math-block'}>
              <label
                text={token.content}
                class="text-base text-slate-700 bg-slate-100 p-3 rounded-lg mb-3 font-mono"
                textWrap={true}
              />
            </Show>
          </>
        )}
      </For>

      {/* Streaming caret */}
      <Show when={showCaret() && isStreamingActive()}>
        <label text={caretChar()} class="text-lg text-gray-400 animate-pulse" />
      </Show>
    </stacklayout>
  );
}

// packages/nstreamdown/svelte/components/Streamdown.svelte
<stackLayout class="streamdown-container">
    {#each tokens as token, index (getTokenKey(index, token))}
        <!-- Headings -->
        {#if isHeading(token)}
            <label
                text={token.content}
                class="{getHeadingClass(getHeadingLevel(token))} text-slate-800 mb-2"
                textWrap={true}
            />
        {/if}

        <!-- Paragraphs -->
        {#if token.type === 'paragraph'}
            <label
                text={token.content}
                class="text-base text-slate-700 mb-3 leading-6"
                textWrap={true}
            />
        {/if}

        <!-- Code blocks -->
        {#if token.type === 'code-block'}
            <stackLayout class="bg-slate-800 rounded-lg p-3 mb-3">
                {#if getLanguage(token)}
                    <label
                        text={getLanguage(token)}
                        class="text-xs text-slate-400 mb-2"
                    />
                {/if}
                <label
                    text={token.content}
                    class="text-sm text-green-400 font-mono"
                    textWrap={true}
                />
            </stackLayout>
        {/if}

        <!-- Blockquotes -->
        {#if token.type === 'blockquote'}
            <stackLayout class="border-l-4 border-slate-300 pl-4 mb-3">
                <label
                    text={token.content}
                    class="text-base text-slate-600 italic"
                    textWrap={true}
                />
            </stackLayout>
        {/if}

        <!-- Ordered lists -->
        {#if token.type === 'list-ordered'}
            <stackLayout class="mb-3">
                {#each token.children || [] as item, itemIndex}
                    <gridLayout columns="auto, *" class="mb-1">
                        <label col="0" text="{itemIndex + 1}." class="text-slate-500 mr-2" />
                        <label col="1" text={item.content} class="text-slate-700" textWrap={true} />
                    </gridLayout>
                {/each}
            </stackLayout>
        {/if}

        <!-- Unordered lists -->
        {#if token.type === 'list-unordered'}
            <stackLayout class="mb-3">
                {#each token.children || [] as item}
                    <gridLayout columns="auto, *" class="mb-1">
                        <label col="0" text="•" class="text-slate-500 mr-2" />
                        <label col="1" text={item.content} class="text-slate-700" textWrap={true} />
                    </gridLayout>
                {/each}
            </stackLayout>
        {/if}

        <!-- Tables -->
        {#if token.type === 'table'}
            <scrollView orientation="horizontal" class="mb-3">
                <stackLayout class="bg-white rounded-lg border border-slate-200">
                    {#each token.children || [] as row, rowIndex}
                        <gridLayout
                            columns={row.children?.map(() => '*').join(', ')}
                            class={rowIndex === 0 ? 'bg-slate-100' : ''}
                        >
                            {#each row.children || [] as cell, cellIndex}
                                <label
                                    col={cellIndex}
                                    text={cell.content}
                                    class="{rowIndex === 0 ? 'font-semibold ' : ''}p-2 text-sm text-slate-700"
                                />
                            {/each}
                        </gridLayout>
                    {/each}
                </stackLayout>
            </scrollView>
        {/if}

        <!-- Images -->
        {#if token.type === 'image'}
            <image
                src={getUrl(token)}
                class="rounded-lg mb-3"
                stretch="aspectFit"
            />
        {/if}

        <!-- Horizontal rules -->
        {#if token.type === 'horizontal-rule'}
            <stackLayout class="h-px bg-slate-200 my-4" />
        {/if}

        <!-- Math blocks -->
        {#if token.type === 'math-block'}
            <label
                text={token.content}
                class="text-base text-slate-700 bg-slate-100 p-3 rounded-lg mb-3 font-mono"
                textWrap={true}
            />
        {/if}
    {/each}

    <!-- Streaming caret -->
    {#if showCaret && isStreamingActive}
        <label text={caretChar} class="text-lg text-gray-400 animate-pulse" />
    {/if}
</stackLayout>

<script lang="ts">
    import { onDestroy } from 'svelte';
    import { parseMarkdown } from '@nstudio/nstreamdown';
    import type { MarkdownToken } from '@nstudio/nstreamdown';

    export interface StreamdownConfig {
        /** Mode: 'streaming' for real-time updates, 'static' for complete markdown */
        mode?: 'streaming' | 'static';
        /** Whether to show copy/download controls */
        controls?: boolean;
        /** Whether to animate the caret during streaming */
        showCaret?: boolean;
        /** Custom caret character */
        caret?: string;
    }

    // Props
    export let content: string = '';
    export let config: StreamdownConfig = {};
    export let isStreaming: boolean = false;

    // Internal state
    let markdown = '';
    let throttleTimer: ReturnType<typeof setTimeout> | null = null;
    let pendingContent = '';
    let lastUpdateTime = 0;
    const THROTTLE_MS = 32;

    // Computed values
    $: mode = config?.mode || 'streaming';
    $: showCaret = config?.showCaret ?? true;
    $: caretChar = config?.caret || '▋';

    // Parse tokens
    $: parsedResult = markdown ? parseMarkdown(markdown, mode === 'streaming') : { tokens: [], isComplete: true };
    $: tokens = parsedResult.tokens;
    $: isComplete = parsedResult.isComplete;
    $: isStreamingActive = mode === 'streaming' && !isComplete;

    // Watch content changes with throttling
    $: {
        const newContent = content;
        const currentMode = mode;

        if (currentMode === 'streaming') {
            pendingContent = newContent;
            const now = Date.now();
            const elapsed = now - lastUpdateTime;

            if (elapsed >= THROTTLE_MS) {
                lastUpdateTime = now;
                markdown = newContent;
            } else if (!throttleTimer) {
                throttleTimer = setTimeout(() => {
                    throttleTimer = null;
                    lastUpdateTime = Date.now();
                    markdown = pendingContent;
                }, THROTTLE_MS - elapsed);
            }
        } else {
            markdown = newContent;
        }
    }

    // Cleanup
    onDestroy(() => {
        if (throttleTimer) {
            clearTimeout(throttleTimer);
            throttleTimer = null;
        }
    });

    // Helper functions
    function isHeading(token: MarkdownToken): boolean {
        return token.type.startsWith('heading');
    }

    function getHeadingLevel(token: MarkdownToken): number {
        return parseInt(token.type.replace('heading', ''), 10) || 1;
    }

    function getLanguage(token: MarkdownToken): string {
        return (token.metadata?.['language'] as string) || '';
    }

    function getUrl(token: MarkdownToken): string {
        return (token.metadata?.['url'] as string) || '';
    }

    function getTokenKey(index: number, token: MarkdownToken): string {
        return `${index}-${token.type}-${token.content?.length || 0}`;
    }

    function getHeadingClass(level: number): string {
        const sizes: Record<number, string> = {
            1: 'text-3xl font-bold',
            2: 'text-2xl font-bold',
            3: 'text-xl font-semibold',
            4: 'text-lg font-semibold',
            5: 'text-base font-medium',
            6: 'text-sm font-medium'
        };
        return sizes[level] || sizes[1];
    }
</script>
