// packages/nstreamdown/vue/components/Streamdown.vue
<script lang="ts" setup>
import { ref, computed, watch, onUnmounted } from 'vue';
import { parseMarkdown, parseInlineFormatting, openUrl, remend } from '@nstudio/nstreamdown';
import type { MarkdownToken } from '@nstudio/nstreamdown';
import CodeBlock from './CodeBlock.vue';
import MdMath from './MdMath.vue';
import MdMermaid from './MdMermaid.vue';
import MdTable from './MdTable.vue';

export interface StreamdownConfig {
  /** Mode: 'streaming' for real-time updates, 'static' for complete markdown */
  mode?: 'streaming' | 'static';
  /** Whether to show copy/download controls */
  controls?: boolean;
  /** Whether to animate the caret during streaming */
  showCaret?: boolean;
  /** Custom caret character */
  caret?: string;
  /** Override body text color for headings, paragraphs, lists, blockquotes (e.g. 'white', '#ffffff'). When not set, default theme colors apply. */
  textColor?: string;
  /** Override link text color (default: blue-600 / #2563eb) */
  linkColor?: string;
  /** Override inline code text color (default: pink-600 / #db2777) */
  codeInlineColor?: string;
  /** Override strikethrough text color (default: slate-400 / #94a3b8) */
  strikethroughColor?: string;
  /** Override inline math text color (default: blue-800 / #1e40af) */
  mathInlineColor?: string;
}

interface Props {
  content: string;
  config?: StreamdownConfig;
  isStreaming?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  content: '',
  config: () => ({}),
  isStreaming: false
});

const emit = defineEmits<{
  linkTap: [url: string];
  parseComplete: [];
}>();

// Internal state
const markdown = ref('');
let throttleTimer: ReturnType<typeof setTimeout> | null = null;
let pendingContent = '';
let lastUpdateTime = 0;
const THROTTLE_MS = 32;

// Computed mode value
const mode = computed(() => props.config?.mode || 'streaming');
const showCaret = computed(() => props.config?.showCaret ?? true);
const caretChar = computed(() => props.config?.caret || '▋');

// Parsed tokens
const parsedResult = computed(() => {
  if (!markdown.value) return { tokens: [], isComplete: true };
  const isStreamingMode = mode.value === 'streaming';
  return parseMarkdown(markdown.value, isStreamingMode);
});

const tokens = computed(() => parsedResult.value.tokens);
const isComplete = computed(() => parsedResult.value.isComplete);
const isStreamingActive = computed(() => mode.value === 'streaming' && !isComplete.value);

// Watch content changes with throttling
watch(() => props.content, (newContent) => {
  const currentMode = mode.value;
  
  if (currentMode === 'streaming') {
    pendingContent = newContent;
    const now = Date.now();
    const elapsed = now - lastUpdateTime;
    
    if (elapsed >= THROTTLE_MS) {
      lastUpdateTime = now;
      markdown.value = newContent;
    } else if (!throttleTimer) {
      throttleTimer = setTimeout(() => {
        throttleTimer = null;
        lastUpdateTime = Date.now();
        markdown.value = pendingContent;
      }, THROTTLE_MS - elapsed);
    }
  } else {
    markdown.value = newContent;
  }
}, { immediate: true });

// Cleanup
onUnmounted(() => {
  if (throttleTimer) {
    clearTimeout(throttleTimer);
    throttleTimer = null;
  }
});

// Helper functions
function isHeading(token: MarkdownToken): boolean {
  return token.type.startsWith('heading');
}

function getHeadingLevel(token: MarkdownToken): number {
  return parseInt(token.type.replace('heading', ''), 10) || 1;
}

function getLanguage(token: MarkdownToken): string {
  return (token.metadata?.['language'] as string) || '';
}

function getIsIncomplete(token: MarkdownToken): boolean {
  return (token.metadata?.['isIncomplete'] as boolean) || false;
}

function getUrl(token: MarkdownToken): string {
  return (token.metadata?.['url'] as string) || '';
}

function getHeadingClass(level: number): string {
  const sizes: Record<number, string> = {
    1: 'text-3xl font-bold',
    2: 'text-2xl font-bold',
    3: 'text-xl font-semibold',
    4: 'text-lg font-semibold',
    5: 'text-base font-medium',
    6: 'text-sm font-medium'
  };
  return sizes[level] || sizes[1];
}

// Get inline tokens for content that needs inline formatting
function getInlineTokens(content: string, children?: MarkdownToken[]): MarkdownToken[] {
  if (children && children.length > 0) {
    return children;
  }
  if (content) {
    return parseInlineFormatting(content);
  }
  return [];
}

// Color overrides from config - null means use CSS defaults
const textColorOverride = computed(() => props.config?.textColor || null);
const linkColorOverride = computed(() => props.config?.linkColor || null);
const codeInlineColorOverride = computed(() => props.config?.codeInlineColor || null);
const strikethroughColorOverride = computed(() => props.config?.strikethroughColor || null);
const mathInlineColorOverride = computed(() => props.config?.mathInlineColor || null);

// Handle link taps
function onLinkTap(token: MarkdownToken) {
  const url = token.metadata?.['url'] as string;
  if (url && url !== 'streamdown:incomplete-link') {
    emit('linkTap', url);
    openUrl(url);
  }
}
</script>

<template>
  <StackLayout class="streamdown-container">
    <template v-for="(token, index) in tokens" :key="`${index}-${token.type}-${token.content?.length || 0}`">
      <!-- Headings -->
      <FlexboxLayout
        v-if="isHeading(token)"
        flexWrap="wrap"
        alignItems="center"
        :color="textColorOverride"
        :class="getHeadingClass(getHeadingLevel(token)) + (textColorOverride ? '' : ' text-slate-800') + ' mb-2'"
      >
        <template v-for="(inlineToken, inlineIndex) in getInlineTokens(token.content, token.children)" :key="inlineIndex">
          <Label v-if="inlineToken.type === 'text'" :text="inlineToken.content" :color="textColorOverride" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'bold'" :text="inlineToken.content" :color="textColorOverride" class="font-bold" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'italic'" :text="inlineToken.content" :color="textColorOverride" class="italic" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'bold-italic'" :text="inlineToken.content" :color="textColorOverride" class="font-bold italic" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'code-inline'" :text="inlineToken.content" class="font-mono bg-slate-100 text-pink-600 rounded px-1" :color="codeInlineColorOverride" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'link'" :text="inlineToken.content" class="text-blue-600 underline" :color="linkColorOverride" textWrap="true" ignoreTouchAnimation="true" @tap="onLinkTap(inlineToken)" />
          <Label v-else :text="inlineToken.content" textWrap="true" />
        </template>
      </FlexboxLayout>

      <!-- Paragraphs -->
      <FlexboxLayout
        v-else-if="token.type === 'paragraph'"
        flexWrap="wrap"
        alignItems="center"
        class="mb-3"
      >
        <template v-for="(inlineToken, inlineIndex) in getInlineTokens(token.content, token.children)" :key="inlineIndex">
          <Label v-if="inlineToken.type === 'text'" :text="inlineToken.content" class="text-sm text-slate-700 leading-6" :color="textColorOverride" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'bold'" :text="inlineToken.content" class="text-sm text-slate-800 font-bold leading-6" :color="textColorOverride" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'italic'" :text="inlineToken.content" class="text-sm text-slate-700 italic leading-6" :color="textColorOverride" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'bold-italic'" :text="inlineToken.content" class="text-sm text-slate-800 font-bold italic leading-6" :color="textColorOverride" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'strikethrough'" :text="inlineToken.content" class="text-sm text-slate-400 leading-6" :color="strikethroughColorOverride" textDecoration="line-through" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'code-inline'" :text="inlineToken.content" class="text-xs font-mono bg-slate-100 text-pink-600 rounded px-1" :color="codeInlineColorOverride" textWrap="true" />
          <Label v-else-if="inlineToken.type === 'link'" :text="inlineToken.content" class="text-sm text-blue-600 leading-6 underline" :color="linkColorOverride" textWrap="true" ignoreTouchAnimation="true" @tap="onLinkTap(inlineToken)" />
          <MdMath v-else-if="inlineToken.type === 'math-inline'" :content="inlineToken.content" :block="false" :color="mathInlineColorOverride" />
          <Label v-else :text="inlineToken.content" class="text-sm text-slate-700 leading-6" :color="textColorOverride" textWrap="true" />
        </template>
      </FlexboxLayout>

      <!-- Code blocks -->
      <CodeBlock
        v-else-if="token.type === 'code-block'"
        :code="token.content"
        :language="getLanguage(token)"
        :isIncomplete="getIsIncomplete(token)"
      />

      <!-- Blockquotes -->
      <StackLayout
        v-else-if="token.type === 'blockquote'"
        class="border-l-4 border-slate-300 pl-4 mb-3"
      >
        <FlexboxLayout flexWrap="wrap" alignItems="center">
          <template v-for="(inlineToken, inlineIndex) in getInlineTokens(token.content, token.children)" :key="inlineIndex">
            <Label v-if="inlineToken.type === 'text'" :text="inlineToken.content" class="text-base text-slate-600 italic" :color="textColorOverride" textWrap="true" />
            <Label v-else-if="inlineToken.type === 'bold'" :text="inlineToken.content" class="text-base text-slate-700 font-bold italic" :color="textColorOverride" textWrap="true" />
            <Label v-else-if="inlineToken.type === 'link'" :text="inlineToken.content" class="text-base text-blue-600 italic underline" :color="linkColorOverride" textWrap="true" ignoreTouchAnimation="true" @tap="onLinkTap(inlineToken)" />
            <Label v-else :text="inlineToken.content" class="text-base text-slate-600 italic" :color="textColorOverride" textWrap="true" />
          </template>
        </FlexboxLayout>
      </StackLayout>

      <!-- Ordered lists -->
      <StackLayout
        v-else-if="token.type === 'list-ordered'"
        class="mb-3"
      >
        <GridLayout
          v-for="(item, itemIndex) in token.children"
          :key="itemIndex"
          columns="auto, *"
          class="mb-1"
        >
          <Label col="0" :text="`${itemIndex + 1}.`" class="text-slate-500 mr-2" :color="textColorOverride" />
          <FlexboxLayout col="1" flexWrap="wrap" alignItems="center">
            <template v-for="(inlineToken, inlineIndex) in getInlineTokens(item.content, item.children)" :key="inlineIndex">
              <Label v-if="inlineToken.type === 'text'" :text="inlineToken.content" class="text-sm text-slate-700" :color="textColorOverride" textWrap="true" />
              <Label v-else-if="inlineToken.type === 'bold'" :text="inlineToken.content" class="text-sm text-slate-800 font-bold" :color="textColorOverride" textWrap="true" />
              <Label v-else-if="inlineToken.type === 'italic'" :text="inlineToken.content" class="text-sm text-slate-700 italic" :color="textColorOverride" textWrap="true" />
              <Label v-else-if="inlineToken.type === 'strikethrough'" :text="inlineToken.content" class="text-sm text-slate-400" :color="strikethroughColorOverride" textDecoration="line-through" textWrap="true" />
              <Label v-else-if="inlineToken.type === 'code-inline'" :text="inlineToken.content" class="text-xs font-mono bg-slate-100 text-pink-600 rounded px-1" :color="codeInlineColorOverride" textWrap="true" />
              <Label v-else-if="inlineToken.type === 'link'" :text="inlineToken.content" class="text-sm text-blue-600 underline" :color="linkColorOverride" textWrap="true" ignoreTouchAnimation="true" @tap="onLinkTap(inlineToken)" />
              <Label v-else :text="inlineToken.content" class="text-sm text-slate-700" :color="textColorOverride" textWrap="true" />
            </template>
          </FlexboxLayout>
        </GridLayout>
      </StackLayout>

      <!-- Unordered lists -->
      <StackLayout
        v-else-if="token.type === 'list-unordered'"
        class="mb-3"
      >
        <GridLayout
          v-for="(item, itemIndex) in token.children"
          :key="itemIndex"
          columns="auto, *"
          class="mb-1"
        >
          <Label col="0" text="•" class="text-slate-500 mr-2" :color="textColorOverride" />
          <FlexboxLayout col="1" flexWrap="wrap" alignItems="center">
            <template v-for="(inlineToken, inlineIndex) in getInlineTokens(item.content, item.children)" :key="inlineIndex">
              <Label v-if="inlineToken.type === 'text'" :text="inlineToken.content" class="text-sm text-slate-700" :color="textColorOverride" textWrap="true" />
              <Label v-else-if="inlineToken.type === 'bold'" :text="inlineToken.content" class="text-sm text-slate-800 font-bold" :color="textColorOverride" textWrap="true" />
              <Label v-else-if="inlineToken.type === 'italic'" :text="inlineToken.content" class="text-sm text-slate-700 italic" :color="textColorOverride" textWrap="true" />
              <Label v-else-if="inlineToken.type === 'strikethrough'" :text="inlineToken.content" class="text-sm text-slate-400" :color="strikethroughColorOverride" textDecoration="line-through" textWrap="true" />
              <Label v-else-if="inlineToken.type === 'code-inline'" :text="inlineToken.content" class="text-xs font-mono bg-slate-100 text-pink-600 rounded px-1" :color="codeInlineColorOverride" textWrap="true" />
              <Label v-else-if="inlineToken.type === 'link'" :text="inlineToken.content" class="text-sm text-blue-600 underline" :color="linkColorOverride" textWrap="true" ignoreTouchAnimation="true" @tap="onLinkTap(inlineToken)" />
              <Label v-else :text="inlineToken.content" class="text-sm text-slate-700" :color="textColorOverride" textWrap="true" />
            </template>
          </FlexboxLayout>
        </GridLayout>
      </StackLayout>

      <!-- Tables -->
      <MdTable
        v-else-if="token.type === 'table'"
        :rows="token.children || []"
      />

      <!-- Images -->
      <Image
        v-else-if="token.type === 'image'"
        :src="getUrl(token)"
        class="rounded-lg mb-3"
        stretch="aspectFit"
      />

      <!-- Horizontal rules -->
      <StackLayout
        v-else-if="token.type === 'horizontal-rule'"
        class="h-px bg-slate-200 my-4"
      />

      <!-- Math blocks -->
      <MdMath
        v-else-if="token.type === 'math-block'"
        :content="token.content"
        :block="true"
      />

      <!-- Mermaid diagrams -->
      <MdMermaid
        v-else-if="token.type === 'mermaid'"
        :content="token.content"
        :darkMode="true"
        :isIncomplete="getIsIncomplete(token)"
      />
    </template>

    <!-- Streaming caret -->
    <Label
      v-if="showCaret && isStreamingActive"
      :text="caretChar"
      class="text-lg text-gray-400 animate-pulse"
    />
  </StackLayout>
</template>

// packages/nstreamdown/svelte/components/Streamdown.svelte
<stackLayout class="streamdown-container">
    {#each tokens as token, index (getTokenKey(index, token))}
        <!-- Headings -->
        {#if isHeading(token)}
            <label
                class="{getHeadingClass(getHeadingLevel(token))} {textColorOverride ? '' : 'text-slate-800'} mb-2"
                textWrap={true}
                color={textColorOverride}
            >
                <formattedString>
                    {#each token.children || [{ type: 'text', content: token.content }] as child}
                        {#if child.type === 'bold'}
                            <span text={child.content} class="font-bold" />
                        {:else if child.type === 'italic'}
                            <span text={child.content} class="italic" />
                        {:else if child.type === 'bold-italic'}
                            <span text={child.content} class="font-bold italic" />
                        {:else if child.type === 'code-inline'}
                            <span text={child.content} class="font-mono bg-slate-200 text-pink-600" color={codeInlineColorOverride} />
                        {:else if child.type === 'strikethrough'}
                            <span text={child.content} class="line-through" color={strikethroughColorOverride} />
                        {:else}
                            <span text={child.content} />
                        {/if}
                    {/each}
                </formattedString>
            </label>
        {/if}

        <!-- Paragraphs -->
        {#if token.type === 'paragraph'}
            <label
                class="text-base text-slate-700 mb-3 leading-6"
                textWrap={true}
                color={textColorOverride}
            >
                <formattedString>
                    {#each token.children || [{ type: 'text', content: token.content }] as child}
                        {#if child.type === 'bold'}
                            <span text={child.content} class="font-bold" />
                        {:else if child.type === 'italic'}
                            <span text={child.content} class="italic" />
                        {:else if child.type === 'bold-italic'}
                            <span text={child.content} class="font-bold italic" />
                        {:else if child.type === 'code-inline'}
                            <span text={child.content} class="font-mono bg-slate-200 text-pink-600" color={codeInlineColorOverride} />
                        {:else if child.type === 'strikethrough'}
                            <span text={child.content} class="line-through text-slate-400" color={strikethroughColorOverride} />
                        {:else if child.type === 'link'}
                            <span text={child.content} class="text-blue-600 underline" color={linkColorOverride} />
                        {:else}
                            <span text={child.content} />
                        {/if}
                    {/each}
                </formattedString>
            </label>
        {/if}

        <!-- Code blocks -->
        {#if token.type === 'code-block'}
            <stackLayout class="bg-slate-800 rounded-lg p-3 mb-3">
                {#if getLanguage(token)}
                    <label
                        text={getLanguage(token)}
                        class="text-xs text-slate-400 mb-2"
                    />
                {/if}
                <label
                    text={token.content}
                    class="text-sm text-green-400 font-mono"
                    textWrap={true}
                />
            </stackLayout>
        {/if}

        <!-- Blockquotes -->
        {#if token.type === 'blockquote'}
            <stackLayout class="border-l-4 border-slate-300 pl-4 mb-3">
                <label
                    text={token.content}
                    class="text-base text-slate-600 italic"
                    textWrap={true}
                    color={textColorOverride}
                />
            </stackLayout>
        {/if}

        <!-- Ordered lists -->
        {#if token.type === 'list-ordered'}
            <stackLayout class="mb-3">
                {#each token.children || [] as item, itemIndex}
                    <gridLayout columns="auto, *" class="mb-1">
                        <label col="0" text="{itemIndex + 1}." class="text-slate-500 mr-2" color={textColorOverride} />
                        <label col="1" text={item.content} class="text-slate-700" textWrap={true} color={textColorOverride} />
                    </gridLayout>
                {/each}
            </stackLayout>
        {/if}

        <!-- Unordered lists -->
        {#if token.type === 'list-unordered'}
            <stackLayout class="mb-3">
                {#each token.children || [] as item}
                    <gridLayout columns="auto, *" class="mb-1">
                        <label col="0" text="•" class="text-slate-500 mr-2" color={textColorOverride} />
                        <label col="1" text={item.content} class="text-slate-700" textWrap={true} color={textColorOverride} />
                    </gridLayout>
                {/each}
            </stackLayout>
        {/if}

        <!-- Tables -->
        {#if token.type === 'table'}
            <scrollView orientation="horizontal" class="mb-3">
                <stackLayout class="bg-white rounded-lg border border-slate-200">
                    {#each token.children || [] as row, rowIndex}
                        <gridLayout
                            columns={row.children?.map(() => '*').join(', ')}
                            class={rowIndex === 0 ? 'bg-slate-100' : ''}
                        >
                            {#each row.children || [] as cell, cellIndex}
                                <label
                                    col={cellIndex}
                                    text={cell.content}
                                    class="{rowIndex === 0 ? 'font-semibold ' : ''}p-2 text-sm text-slate-700"
                                />
                            {/each}
                        </gridLayout>
                    {/each}
                </stackLayout>
            </scrollView>
        {/if}

        <!-- Images -->
        {#if token.type === 'image'}
            <image
                src={getUrl(token)}
                class="rounded-lg mb-3"
                stretch="aspectFit"
            />
        {/if}

        <!-- Horizontal rules -->
        {#if token.type === 'horizontal-rule'}
            <stackLayout class="h-px bg-slate-200 my-4" />
        {/if}

        <!-- Math blocks -->
        {#if token.type === 'math-block'}
            <label
                text={token.content}
                class="text-base text-slate-700 bg-slate-100 p-3 rounded-lg mb-3 font-mono"
                textWrap={true}
            />
        {/if}

        <!-- Mermaid diagrams -->
        {#if token.type === 'mermaid-block'}
            <MdMermaid
                content={token.content}
                darkMode={true}
            />
        {/if}
    {/each}

    <!-- Streaming caret -->
    {#if showCaret && isStreamingActive}
        <label text={caretChar} class="text-lg text-gray-400 animate-pulse" />
    {/if}
</stackLayout>

<script lang="ts">
    import { onDestroy } from 'svelte';
    import { parseMarkdown } from '@nstudio/nstreamdown';
    import type { MarkdownToken } from '@nstudio/nstreamdown';
    import MdMermaid from './MdMermaid.svelte';

    export interface StreamdownConfig {
        /** Mode: 'streaming' for real-time updates, 'static' for complete markdown */
        mode?: 'streaming' | 'static';
        /** Whether to show copy/download controls */
        controls?: boolean;
        /** Whether to animate the caret during streaming */
        showCaret?: boolean;
        /** Custom caret character */
        caret?: string;
        /** Override body text color for headings, paragraphs, lists, blockquotes (e.g. 'white', '#ffffff'). When not set, default theme colors apply. */
        textColor?: string;
        /** Override link text color (default: blue-600 / #2563eb) */
        linkColor?: string;
        /** Override inline code text color (default: pink-600 / #db2777) */
        codeInlineColor?: string;
        /** Override strikethrough text color (default: slate-400 / #94a3b8) */
        strikethroughColor?: string;
        /** Override inline math text color (default: blue-800 / #1e40af) */
        mathInlineColor?: string;
    }

    // Props
    export let content: string = '';
    export let config: StreamdownConfig = {};

    // Internal state
    let markdown = '';
    let throttleTimer: ReturnType<typeof setTimeout> | null = null;
    let pendingContent = '';
    let lastUpdateTime = 0;
    const THROTTLE_MS = 32;

    // Computed values
    $: mode = config?.mode || 'streaming';
    $: showCaret = config?.showCaret ?? true;
    $: caretChar = config?.caret || '▋';

    // Color overrides from config
    $: textColorOverride = config?.textColor || undefined;
    $: linkColorOverride = config?.linkColor || undefined;
    $: codeInlineColorOverride = config?.codeInlineColor || undefined;
    $: strikethroughColorOverride = config?.strikethroughColor || undefined;
    $: mathInlineColorOverride = config?.mathInlineColor || undefined;

    // Parse tokens
    $: parsedResult = markdown ? parseMarkdown(markdown, mode === 'streaming') : { tokens: [], isComplete: true };
    $: tokens = parsedResult.tokens;
    $: isComplete = parsedResult.isComplete;
    $: isStreamingActive = mode === 'streaming' && !isComplete;

    // Watch content changes with throttling
    $: {
        const newContent = content;
        const currentMode = mode;

        if (currentMode === 'streaming') {
            pendingContent = newContent;
            const now = Date.now();
            const elapsed = now - lastUpdateTime;

            if (elapsed >= THROTTLE_MS) {
                lastUpdateTime = now;
                markdown = newContent;
            } else if (!throttleTimer) {
                throttleTimer = setTimeout(() => {
                    throttleTimer = null;
                    lastUpdateTime = Date.now();
                    markdown = pendingContent;
                }, THROTTLE_MS - elapsed);
            }
        } else {
            markdown = newContent;
        }
    }

    // Cleanup
    onDestroy(() => {
        if (throttleTimer) {
            clearTimeout(throttleTimer);
            throttleTimer = null;
        }
    });

    // Helper functions
    function isHeading(token: MarkdownToken): boolean {
        return token.type.startsWith('heading');
    }

    function getHeadingLevel(token: MarkdownToken): number {
        return parseInt(token.type.replace('heading', ''), 10) || 1;
    }

    function getLanguage(token: MarkdownToken): string {
        return (token.metadata?.['language'] as string) || '';
    }

    function getUrl(token: MarkdownToken): string {
        return (token.metadata?.['url'] as string) || '';
    }

    function getTokenKey(index: number, token: MarkdownToken): string {
        return `${index}-${token.type}-${token.content?.length || 0}`;
    }

    function getHeadingClass(level: number): string {
        const sizes: Record<number, string> = {
            1: 'text-3xl font-bold',
            2: 'text-2xl font-bold',
            3: 'text-xl font-semibold',
            4: 'text-lg font-semibold',
            5: 'text-base font-medium',
            6: 'text-sm font-medium'
        };
        return sizes[level] || sizes[1];
    }
</script>
