// apps/demo-react/src/components/App.tsx
import * as React from "react";
import { useState } from "react";
import { FrameNavigationProp } from "react-nativescript-navigation";
import { Home } from "./Home";
import { StreamdownDemo } from "./StreamdownDemo";
import { ChatDemo } from "./ChatDemo";

// Simple navigation state
type Screen = 'home' | 'demo' | 'chat';

export const App = () => {
    const [currentScreen, setCurrentScreen] = useState<Screen>('home');

    const navigate = (screen: Screen) => {
        setCurrentScreen(screen);
    };

    const goBack = () => {
        setCurrentScreen('home');
    };

    return (
        <frame>
            {currentScreen === 'home' && <Home onNavigate={navigate} />}
            {currentScreen === 'demo' && <StreamdownDemo onBack={goBack} />}
            {currentScreen === 'chat' && <ChatDemo onBack={goBack} />}
        </frame>
    );
};

// apps/demo-solid/src/app.jsx
import { createSignal } from 'solid-js';
import { Home } from './components/Home';
import { StreamdownDemo } from './components/StreamdownDemo';
import { ChatDemo } from './components/ChatDemo';

const App = () => {
  const [currentScreen, setCurrentScreen] = createSignal('home');

  const navigate = (screen) => {
    setCurrentScreen(screen);
  };

  const goBack = () => {
    setCurrentScreen('home');
  };

  return (
    <frame>
      {currentScreen() === 'home' && <Home onNavigate={navigate} />}
      {currentScreen() === 'demo' && <StreamdownDemo onBack={goBack} />}
      {currentScreen() === 'chat' && <ChatDemo onBack={goBack} />}
    </frame>
  );
};

export { App };
